### ISSUE TITLE
A doubt regarding the TFX pipeline associated with Continuous Training

### ISSUE THREAD

**Issue by sayakpaul** [GoogleCloudPlatform/mlops-with-vertex-ai#1]
Hi @ksalama. 

Thank you very much for this amazing resource. It's a mini-book in itself. 

I am referring to the statement written just below the continuous training section:

> The end-to-end TFX training pipeline implementation is in the src/pipelines directory, which covers the following steps:

Are these pipelines demonstrated in any of the notebooks?

**Comment by ksalama** [comment]
Yes, the components of the pipeline are executed individually in the 03-training-formalization.ipynb notebook, and the pipeline is executed using a local runner in the 04-pipeline-deployment.ipynb notebook:
```!py.test src/tests/pipeline_deployment_tests.py::test_e2e_pipeline -s```
