### ISSUE TITLE
Error during compilation with Cloud Build

### ISSUE THREAD

**Issue by sayakpaul** [GoogleCloudPlatform/mlops-with-vertex-ai#2]
During the training pipeline compilation phase with Cloud Build I am facing a weird error.

Here's the entire compilation log. 
[log-41d61716-bd25-434c-ae3c-745540d398b8.log.zip](https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai/files/6901935/log-41d61716-bd25-434c-ae3c-745540d398b8.log.zip)

**Comment by ksalama** [comment]
I have updated the code to use TFX 1.2 and TF 2.5. Can you please check now if the issue is still working?
